models:
  Linear_reg:
    param_grid:
      n_jobs:
        - -1

  Logistic_reg:
    param_grid:
      solver:
        - lbfgs
        - liblinear
        - newton-cg
      max_iter:
        - 1000
        - 3000

  KNN_neighbors_reg:
    param_grid:
      n_neighbors: 
        - 3
        - 5
        - 7
      weights: 
        - uniform
        - distance
      algorithm: 
        - ball_tree
        - kd_tree
      leaf_size:
        - 30
        - 60
        - 90
      p:
        - 1
        - 2

  Decision_tree_reg:
    param_grid:
      criterion: 
        - gini
        - entropy
      splitter: 
        - best
        - random
      max_depth: 
        - null
        - 5
        - 10
      min_samples_split: 
        - 2
        - 5
        - 10
      min_samples_leaf: 
        - 1
        - 2
        - 4

  Extra_trees_reg:
    param_grid:
      criterion: 
        - gini
        - entropy
      max_depth: 
        - null
        - 5
        - 10
      min_samples_split: 
        - 2
        - 5
        - 10
      min_samples_leaf: 
        - 1
        - 2
        - 4

  Random_forest_reg:
    param_grid:
      n_estimators: 
        - 8
        - 16
        - 32
        - 64
        - 128
        - 256
      criterion:
        - squared_error
        - friedman_mse
        - absolute_error
        - poisson
      max_features:
        - sqrt
        - log2
      max_depth: 
        - null
        - 5
        - 10
      min_samples_split: 
        - 2
        - 5
        - 10
      min_samples_leaf: 
        - 1
        - 2
        - 4

  Gradient_boost_reg:
    param_grid:
      n_estimators:
        - 8
        - 16
        - 32
        - 64
        - 128
        - 256
      learning_rate:
        - 0.1
        - 0.01
        - 0.05
        - 0.001
      subsample:
        - 0.6
        - 0.7
        - 0.75
        - 0.8
        - 0.85
        - 0.9
      criterion:
        - friedman_mse
        - squared_error
      max_depth:
        - 3
        - 5
        - 7

  Ada_boost_reg:
    param_grid:
      n_estimators:
        - 8
        - 16
        - 32
        - 64
        - 128
        - 256
      learning_rate:
        - 0.1
        - 0.01
        - 0.05
        - 0.001

  XG_boost_reg:
    param_grid:
      learning_rate: 
        - 0.1
        - 0.01
        - 0.001
      max_depth: 
        - 3
        - 5
        - 7
      n_estimators: 
        - 8
        - 16
        - 32
        - 64
        - 128
        - 256
      gamma: 
        - 0
        - 0.1
        - 0.2

  Cat_boost_reg:
    param_grid:
      depth:
        - 6
        - 8
        - 10
      learning_rate: 
        - 0.1
        - 0.01
        - 0.05
      iterations:
        - 30
        - 50
        - 100
